/**
 * Building templates for addBuilding(). Interiors are drawn with the street
 * door (+) on the bottom edge; the model flips them for north-facing doors.
 * footprint: [width, height] of the solid block stamped on the world canvas.
 * beds / counter: interior tile coordinates offered as home and work places.
 */
export const BUILDINGS = [
    {
        id: 'shop', name: 'General store', footprint: [14, 9], open: true,
        description: 'Shelves of candles, rope, dried herbs and wrapped meals. A long counter keeps goods and customers politely apart.',
        lighting: {artificial: 1, daylightAccess: 0.6, tone: 'warm'}, counter: [15, 4], beds: [],
        interior: [
            '####################',
            '#..................#',
            '#.====........====.#',
            '#..................#',
            '#......========....#',
            '#..................#',
            '#..................#',
            '#..................#',
            '#.TT...............#',
            '#.TT...............#',
            '#..................#',
            '##########+#########',
        ],
    },
    {
        id: 'house', name: 'House', footprint: [8, 7], open: false,
        description: 'A tidy two-room house with a sleeping mat and a worn table.',
        lighting: {artificial: 0.8, daylightAccess: 0.5, tone: 'warm'}, beds: [[10, 3]],
        interior: [
            '##############',
            '#............#',
            '#..TT........#',
            '#..TT........#',
            '#............#',
            '#............#',
            '#.===........#',
            '#............#',
            '#######+######',
        ],
    },
    {
        id: 'cottage', name: 'Family cottage', footprint: [8, 7], open: false,
        description: 'A low family cottage with a shared table and two sleeping nooks along the back wall.',
        lighting: {artificial: 0.8, daylightAccess: 0.5, tone: 'warm'}, beds: [[2, 2], [9, 2]],
        interior: [
            '############',
            '#..........#',
            '#..........#',
            '#..........#',
            '#....TT....#',
            '#....TT....#',
            '#..........#',
            '#..........#',
            '#..........#',
            '######+#####',
        ],
    },
    {
        id: 'lodging', name: 'Lodging hall', footprint: [17, 9], open: false,
        description: 'A shared lodging hall. Screened sleeping bays line the back wall behind a long communal table.',
        lighting: {artificial: 1, daylightAccess: 0.4, tone: 'warm'}, beds: [[2, 2], [6, 2], [11, 2], [17, 2], [21, 2]],
        interior: [
            '########################',
            '#...T...T.......T...T..#',
            '#...T...T.......T...T..#',
            '#...T...T.......T...T..#',
            '#......................#',
            '#......................#',
            '#.......TTTTTTTT.......#',
            '#.......TTTTTTTT.......#',
            '#......................#',
            '#......................#',
            '#......................#',
            '############+###########',
        ],
    },
    {
        id: 'barracks', name: 'Barracks', footprint: [17, 10], open: true,
        description: 'Bunk bays with straw ticks, a rack of staves and a scarred mess table. The captain keeps a partitioned room.',
        lighting: {artificial: 1, daylightAccess: 0.3, tone: 'neutral'}, beds: [[3, 2], [6, 2], [9, 2], [12, 2], [16, 2], [22, 2]],
        interior: [
            '##########################',
            '#....T..T..T..T...#......#',
            '#....T..T..T..T...#......#',
            '#....T..T..T..T...#......#',
            '#........................#',
            '#.................#..TTT.#',
            '#.................#......#',
            '#........................#',
            '#........TTTTTT..........#',
            '#........TTTTTT..........#',
            '#.=====..................#',
            '#........................#',
            '#........................#',
            '#############+############',
        ],
    },
    {
        id: 'tavern', name: 'Tavern', footprint: [16, 10], open: true,
        description: 'Warm ash and steeping juniper cling to the rafters. Low tables and broad resting mats gather around the hearth.',
        lighting: {artificial: 1, daylightAccess: 0.5, tone: 'warm'}, counter: [9, 5], beds: [[26, 3], [28, 6]],
        interior: [
            '################################',
            '#......................#.......#',
            '#......................#.......#',
            '#......................#.......#',
            '#....=========.........#.......#',
            '#......................#.......#',
            '#..............................#',
            '#......................#.......#',
            '#......................#.......#',
            '#....TTT...............#########',
            '#....TTT.......................#',
            '#..............................#',
            '#..............................#',
            '#..............................#',
            '#..........TTT........TTT......#',
            '#..........TTT........TTT......#',
            '#.....TT.......................#',
            '#.....TT.......................#',
            '#..............................#',
            '################+###############',
        ],
    },
];

export const buildingById = id => BUILDINGS.find(b => b.id === id) ?? null;
