// Hand-written types for terrain.generated.mjs (generated by tools/terrain_catalog.py from Data/Terrain/terrain.json).

export type TerrainCategoryId = 'ground' | 'nature' | 'elevation' | 'structure' | 'furniture' | 'civic';
export type TerrainKind = 'floor' | 'grass' | 'water' | 'wall' | 'table' | 'counter' | 'stairs' | 'slope' | 'cliff' | 'feature';
export interface TerrainCategory { readonly id: TerrainCategoryId; readonly name: string }
/** One terrain tile: stored as `code`, drawn as `glyph` (or `ascii` in plain-text views). */
export interface TerrainTile {
    readonly code: string; readonly glyph: string; readonly ascii: string; readonly name: string;
    readonly category: TerrainCategoryId; readonly kind: TerrainKind;
    readonly solid: boolean; readonly opaque: boolean; readonly height: number; readonly stature: number;
    readonly cost: number; readonly ramp: boolean; readonly fg: string; readonly bg: string; readonly effect: string;
}
export const TERRAIN_CATEGORIES: readonly TerrainCategory[];
export const TERRAIN: readonly TerrainTile[];
