#!/usr/bin/env python3
"""The terrain catalog: one list of tiles for the server, the game client, Atlas and the tools.

  python3 tools/terrain_catalog.py           regenerate the C++ and editor tables from Data/Terrain/terrain.json
  python3 tools/terrain_catalog.py --check   fail if a generated table is out of date

Python tools import this module for the glyph set and tile rules instead of keeping their own copies.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'Data/Terrain/terrain.json'
CPP = ROOT / 'Source/RATWMUD/Core/RatwTerrainCatalog.inc'
JS = ROOT / 'Editor/src/model/terrain.generated.mjs'
DM_JS = ROOT / 'DM/terrain.generated.mjs'  # The older Storykeeper UI loads its own copy.
KINDS = ('floor', 'grass', 'water', 'wall', 'table', 'counter', 'stairs', 'slope', 'cliff', 'feature')
HEADER = 'Generated by tools/terrain_catalog.py from Data/Terrain/terrain.json. Do not edit.'


class CatalogError(ValueError):
    pass


def _check(ok, message):
    if not ok:
        raise CatalogError(message)


def load(path: Path = SOURCE) -> list[dict]:
    """The tiles with every field filled in, in catalog order; raises CatalogError when the file is unsound."""
    data = json.loads(path.read_text(encoding='utf-8'))
    _check(data.get('format') == 'ratw-terrain' and data.get('version') == 1, 'Not a version 1 terrain catalog.')
    categories = {c['id'] for c in data['categories']}
    tiles, seen = [], set()
    for raw in data['tiles']:
        t = {'solid': False, 'opaque': False, 'height': 0.0, 'stature': 0.0, 'cost': 1.0, 'ramp': False, **raw}
        code = t['code']
        _check(isinstance(code, str) and len(code) == 1 and '!' <= code <= '~', f'{code!r}: a code is one printable ASCII character.')
        _check(code not in seen, f'{code!r}: duplicate code.')
        seen.add(code)
        _check(isinstance(t['glyph'], str) and len(t['glyph']) == 1 and ord(t['glyph']) < 0x10000 and t['glyph'] not in 'W>',
               f'{code!r}: a glyph is one Basic Multilingual Plane character, never the wolf token W or its > marker.')
        _check(isinstance(t['ascii'], str) and len(t['ascii']) == 1 and ' ' < t['ascii'] <= '~', f'{code!r}: ascii fallback must be printable.')
        _check(t['kind'] in KINDS and t['category'] in categories, f'{code!r}: unknown kind or category.')
        _check(all(re.fullmatch(r'#[0-9a-f]{6}', t[k]) for k in ('fg', 'bg')), f'{code!r}: colours are #rrggbb.')
        _check(t['height'] * 2 == int(t['height'] * 2) and -16 <= t['height'] <= 16, f'{code!r}: height is a half step.')
        _check(0 <= t['stature'] <= 8 and 0.5 <= t['cost'] <= 5, f'{code!r}: stature or cost out of range.')
        _check(not (t['opaque'] and not t['solid']), f'{code!r}: an opaque tile must be solid.')
        tiles.append(t)
    return tiles


TILES = load()
BY_CODE = {t['code']: t for t in TILES}
GLYPHS = frozenset(BY_CODE)
SOLID = frozenset(c for c, t in BY_CODE.items() if t['solid'])
RAMPS = frozenset(c for c, t in BY_CODE.items() if t['ramp'])
DEFAULT_HEIGHTS = {c: t['height'] for c, t in BY_CODE.items() if t['height']}


def cpp_table(tiles) -> str:
    def num(v):
        return repr(float(v))
    rows = [f'// {HEADER}',
            '// RATW_TERRAIN(code, Kind, solid, opaque, height, stature, cost, ramp, glyph, ascii, fg, bg, name)']
    for t in tiles:
        rows.append(
            f'RATW_TERRAIN({ord(t["code"]):#04x}, {t["kind"].capitalize()}, {str(t["solid"]).lower()}, '
            f'{str(t["opaque"]).lower()}, {num(t["height"])}, {num(t["stature"])}, {num(t["cost"])}, '
            f'{str(t["ramp"]).lower()}, {ord(t["glyph"]):#06x}, {ord(t["ascii"]):#04x}, 0x{t["fg"][1:]}, '
            f'0x{t["bg"][1:]}, {json.dumps(t["name"], ensure_ascii=True)})')
    return '\n'.join(rows) + '\n'


def js_module(path: Path, tiles) -> str:
    data = json.loads(path.read_text(encoding='utf-8'))
    fields = ('code', 'glyph', 'ascii', 'name', 'category', 'kind', 'solid', 'opaque', 'height', 'stature', 'cost',
              'ramp', 'fg', 'bg', 'effect')
    lines = [f'// {HEADER}', '/** Terrain categories, in palette order. */',
             f'export const TERRAIN_CATEGORIES = {json.dumps(data["categories"], ensure_ascii=False)};',
             '/** Every terrain tile, in palette order. */', 'export const TERRAIN = [']
    lines += [f'    {json.dumps({k: t[k] for k in fields}, ensure_ascii=False)},' for t in tiles]
    lines.append('];')
    return '\n'.join(lines) + '\n'


def outputs() -> dict[Path, str]:
    return {CPP: cpp_table(TILES), JS: js_module(SOURCE, TILES), DM_JS: js_module(SOURCE, TILES)}


def main(argv):
    stale = [p for p, text in outputs().items() if not p.exists() or p.read_text(encoding='utf-8') != text]
    if '--check' in argv:
        for p in stale:
            print(f'Out of date: {p.relative_to(ROOT)} (run python3 tools/terrain_catalog.py)')
        return 1 if stale else 0
    for p, text in outputs().items():
        p.write_text(text, encoding='utf-8')
    print(f'{len(TILES)} tiles; wrote {", ".join(str(p.relative_to(ROOT)) for p in outputs())}')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
